apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-k8s
  template:
    metadata:
      labels:
        app: springboot-k8s
    spec:
      containers:
        - name: springboot-k8s
          image: journal-k8s:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8282
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://host.docker.internal:3306/practice?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: host.docker.internal:9092

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service-v2
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 8282
      nodePort: 30012
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql-service
#spec:
#  selector:
#    app: mysql
#  ports:
#    - protocol: TCP
#      port: 3306
#      targetPort: 3306
